name: 'google_ads_integration_tests'
version: '1.0.0'
profile: 'integration_tests'
config-version: 2

vars:
  google_ads__final_url_performance: "{{ ref('google_ads_final_url_performance_data') }}"
  google_ads__click_performance: "{{ ref('google_ads_click_performance_data') }}"
  google_ads__criteria_performance: "{{ ref('google_ads_criteria_performance_data') }}"

seeds:
  google_ads_integration_tests:
    google_ads_click_performance_data:
      +column_types:
        ad_group_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        campaign_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        criteria_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        external_customer_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
    google_ads_criteria_performance_data:
      +column_types:
        ad_group_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        campaign_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        external_customer_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
    google_ads_final_url_performance_data:
      +column_types:
        ad_group_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        campaign_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        external_customer_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"