name: 'pinterest_source'
version: '0.2.0'
config-version: 2
require-dbt-version: [">=0.18.0", "<0.20.0"]

vars:
  ad_group_history: "{{ source('pinterest_ads','ad_group_history') }}"
  campaign_history: "{{ source('pinterest_ads','campaign_history') }}"
  pin_promotion_history: "{{ source('pinterest_ads','pin_promotion_history') }}"
  pin_promotion_report: "{{ source('pinterest_ads','pin_promotion_report') }}"

models:
  pinterest_source:
    +materialized: table
    tmp:
      +materialized: view