name: 'ad_reporting'
version: '1.0.0'
config-version: 2

require-dbt-version: [">=0.18.0", "<0.20.0"]

vars:
  ad_reporting__pinterest_enabled: true
  ad_reporting__microsoft_ads_enabled: true
  ad_reporting__linkedin_ads_enabled: true
  ad_reporting__google_ads_enabled: true
  ad_reporting__twitter_ads_enabled: true
  ad_reporting__facebook_ads_enabled: true

models:
  ad_reporting:
    +materialized: view
  
  pinterest:
    enabled: true
  pinterest_source:
    enabled: true
  
  microsoft_ads:
    enabled: true
  microsoft_ads_source:
    enabled: true
  
  linkedin:
    enabled: true
  linkedin_source:
    enabled: true
  
  twitter_ads:
    enabled: true
  twitter_ads_source:
    enabled: true
  
  facebook_ads:
    enabled: true
  facebook_ads_source:
    enabled: true
  facebook_ads_creative_history:
    enabled: true
  
  google_ads:
    enabled: true
  google_ads_source:
    enabled: true